name = "caretakerd"
main = "src/index.ts"
compatibility_date = "2023-12-19"
account_id = "76cbc9ff3d45b6d0e9963e41ddeb9b71"

kv_namespaces = [
    { binding = "CACHE", id = "0ea59696afaf4d3893499f0f5e06f880", preview_id = "2df54f10101e42bc95adf9cafe119763" }
]

node_compat = true

[site]
bucket = "./public"
