name = "caretakerd"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "76cbc9ff3d45b6d0e9963e41ddeb9b71"

kv_namespaces = [
    { binding = "CACHE", id = "0ea59696afaf4d3893499f0f5e06f880", preview_id = "2df54f10101e42bc95adf9cafe119763" }
]

[site]
bucket = "./public"
